In [1]:
import pandas as pd
from time import sleep
from tqdm import tqdm
import requests
from io import StringIO
import os

In [2]:
TARGET_YEAR = '2022'

In [3]:
def check_YYYY(YYYY):
    if not (isinstance(YYYY, str) and len(YYYY) == 4 and YYYY.isdigit()):
        raise ValueError("Invalid year: expected a four-digit string.")
    return True

In [4]:
def clean_names(old_cols):
    new_cols = [c.lower().replace('#', '') for c in old_cols]
    return(new_cols)

In [5]:
def read_html_clean(url):
    # replacing bad character, which will cause read_html to fail directly, even with encoding='utf8'
    raw_html = requests.get(url).text
    raw_html = raw_html.replace('\x93', ' ')
    return(raw_html)

In [6]:
def get_events(YYYY):
    check_YYYY(YYYY)
    url = f"https://rusa.org/cgi-bin/resultsearch_PF.pl?regid=&date={YYYY}&type=&dist=&rtid=&esortby=cert&collapse=0"
    print(url)
        
    html_input = read_html_clean(url)
    
    # get versions with and without links
    dat_links = pd.read_html(StringIO(str(html_input)), extract_links='all')[0]
    dat = pd.read_html(StringIO(str(html_input)))[0]
    
    # break apart tuples to get urls. we'll have columns called 0 and 1
        # TODO: validate it contains Route and select columns
    route_ids = pd.DataFrame(dat_links[('Route', None)].tolist(), 
                             index=dat_links.index)
    event_ids = pd.DataFrame(dat_links[('select', None)].tolist(), 
                             index=dat_links.index)

    # extract ids from link urls in column 1
        # TODO validate regex, in case format changes
    dat['rt_url'] = route_ids[1]
    dat['rtid'] = route_ids[1].str.extract('^.*rtid=(.*)')
    dat['event_url'] = event_ids[1]
    dat['eid'] = event_ids[1].str.extract('^.*eid=(.*)&')
    
    # clean col names
    new_cols = [c.lower() for c in list(dat.columns)]
    dat.columns = new_cols

    # drop first row and the 'select' column
    dat = dat.drop(0, axis=0)
    dat = dat.drop('select', axis=1)

    return(dat)

In [7]:
events = get_events(TARGET_YEAR)
events.head()

https://rusa.org/cgi-bin/resultsearch_PF.pl?regid=&date=2022&type=&dist=&rtid=&esortby=cert&collapse=0

,region,club,type,distance,date,route,rt_url,rtid,event_url,eid
1,TX: Dallas,Lone Star Randonneurs / 943026,RUSAP,107,2022/01/01,Willow Park Granbury Lollipop,/cgi-bin/routesearch_PF.pl?rtid=2600,2600,/cgi-bin/resultsearch_PF.pl?eid=12810&esortby=...,12810
2,OR: Portland,Oregon Randonneurs / 937020,RUSAP,109,2022/01/01,Wine Country,/cgi-bin/routesearch_PF.pl?rtid=53,53,/cgi-bin/resultsearch_PF.pl?eid=13567&esortby=...,13567
3,CA: Davis,Davis Bike Club / 905014,RUSAP,102,2022/01/01,Bella Bru 102k,/cgi-bin/routesearch_PF.pl?rtid=2011,2011,/cgi-bin/resultsearch_PF.pl?eid=13156&esortby=...,13156
4,GA: Atlanta,Audax Atlanta / 910004,ACPB,200,2022/01/01,Athens Georgia 200k,/cgi-bin/routesearch_PF.pl?rtid=1141,1141,/cgi-bin/resultsearch_PF.pl?eid=12795&esortby=...,12795
5,CA: Davis,Davis Bike Club / 905014,ACPB,200,2022/01/01,Davis-Auburn-Davis 200Km,/cgi-bin/routesearch_PF.pl?rtid=1162,1162,/cgi-bin/resultsearch_PF.pl?eid=13155&esortby=...,13155

In [13]:
events.tail()

,region,club,type,distance,date,route,rt_url,rtid,event_url,eid
1044,CA: San Diego,San Diego Randonneurs / 905140,RUSAB,203.0,2024/12/28,Missions 200k,/cgi-bin/routesearch_PF.pl?rtid=2545,2545,/cgi-bin/resultsearch_PF.pl?eid=16998&esortby=...,16998
1045,AZ: Phoenix,Arizona Randonneurs / 903020,RUSAP,119.0,2024/12/28,Humboldt Hill Climb,/cgi-bin/routesearch_PF.pl?rtid=2891,2891,/cgi-bin/resultsearch_PF.pl?eid=16160&esortby=...,16160
1046,CA: Davis,Davis Bike Club / 905014,RUSAP,103.0,2024/12/31,Moskowite Corner 100Km,/cgi-bin/routesearch_PF.pl?rtid=1322,1322,/cgi-bin/resultsearch_PF.pl?eid=15734&esortby=...,15734
1047,CA: Davis,Davis Bike Club / 905014,ACPB,200.0,2024/12/31,Davis - Pope Valley - Davis,/cgi-bin/routesearch_PF.pl?rtid=1200,1200,/cgi-bin/resultsearch_PF.pl?eid=15733&esortby=...,15733
1048,NY: Central/Western,Finger Lakes Randonneurs / 932007,RUSAB,201.0,2024/12/31,200LR_3 Womens Rights Loop,/cgi-bin/routesearch_PF.pl?rtid=1082,1082,/cgi-bin/resultsearch_PF.pl?eid=16999&esortby=...,16999

In [8]:
def get_event_details_results(eid):
    
    event_url = f"https://rusa.org/cgi-bin/resultsearch_PF.pl?eid={eid}&esortby=cert"
    #print(event_url)
    two_dats = pd.read_html(event_url)
    
    event_details = two_dats[0]
    event_details.columns = clean_names(list(event_details.columns))
    event_details['eid'] = eid

    # warn if we only get one table back
    if(len(two_dats)<2):
        #print(f'Warning: no finisher results for event {eid}!')
        event_results = pd.DataFrame()
    else:
        event_results = two_dats[1]
        event_results.columns = clean_names(list(event_results.columns))
        # drop the rows 'x nonmembers also finished'
        try:
            event_results = event_results.drop(
                event_results[event_results.cert.str.contains('also finished')].index
            )
        except:
            pass
            #print(f"eid {eid} - couldn't drop 'non member' result rows")
        event_results['eid'] = eid
    
    return([event_details,event_results])

In [9]:
events.groupby('type').size()

type
ACPB     553
ACPF      12
ACPR       2
RM         8
RUSAB    111
RUSAF     23
RUSAP    208
UAFB      11
dtype: int64

In [10]:
# https://rusa.org/pages/eventtypes
non_team_types = ['ACPB', 'RM', 'RUSAB', 'RUSAP']

In [11]:
# list of event ids for the non team event types, for which we'll get results/details
event_ids = events[events.type.isin(non_team_types)].eid.to_list()
print(len(event_ids))

880

In [12]:
e_detail_list = []
e_results_list = []

In [13]:
remaining_event_ids = event_ids #[0:100]

In [17]:
# this can fail with too many event_ids (eg 1034 for 2023)
for e in tqdm(remaining_event_ids):
    this_d_e = get_event_details_results(e)
    e_detail_list.append(this_d_e[0])
    e_results_list.append(this_d_e[1])
    # sleep roughly every nth call (assuming event ids are consecutive ints)
    if(int(e) % 15 == 0):
        sleep(.5)

100%|████████████████████████████████████████████████████████████████████████████████████| 874/874 [10:59<00:00,  1.32it/s]

In [18]:
# should all be the same
print(len(e_detail_list), len(e_results_list), len(event_ids))

880 880 880

In [16]:
# use this if loop fails before completion, then you can rerun the loop cell
remaining_event_ids = event_ids[len(e_detail_list):]

In [19]:
event_results = pd.concat(e_results_list)
event_details = pd.concat(e_detail_list)

In [ ]:
# for when i forgot to filter team events before getting results; 
# the format is different and messes stuff up, plus i don't care about those results right now
# erl2 = list(compress(e_results_list, 
#                      events.type.isin(non_team_types)))

In [20]:
event_details.reset_index(inplace=True, drop=True)
event_results.reset_index(inplace=True, drop=True)

In [21]:
event_results.head()

,cert,rusa,name,club / acp code,time,medal,eid
0,923390,5844,"AURIEMMA, Philip J",San Francisco Randonneurs / 905030,09:47,NaN,15716
1,923391,10133,"BERNHARDT, Luis",San Francisco Randonneurs / 905030,09:43,NaN,15716
2,923392,16644,"BURGHART, Dan",Randonneurs USA / 905095,09:51,Y,15716
3,923393,16048,"CARILLO, Christian R",Randonneurs USA / 905095,08:58,NaN,15716
4,923394,14197,"MANN, Deirdre",Adobo Velo Filipino - American Cycling Club / ...,09:47,NaN,15716

In [22]:
event_details.head()

,region,club,type,distance,date,finishers,dnf,eid
0,CA: Davis,Davis Bike Club / 905014,ACPB,200.0,2024/01/01,9,0.0,15716
1,NC: Asheville,Asheville International Randonneurs / 933011,RUSAP,100.0,2024/01/01,9,0.0,15381
2,TX: Austin,Hill Country Randonneurs / 943025,ACPB,200.0,2024/01/01,2,0.0,15487
3,TX: Dallas,Lone Star Randonneurs / 943026,ACPB,200.0,2024/01/01,5,0.0,15416
4,CA: Los Angeles,Pacific Coast Highway Randonneurs / 905051,ACPB,200.0,2024/01/01,11,0.0,15392

In [23]:
if not os.path.exists('raw_data'):
    os.makedirs('raw_data')
    print('created output dir')

In [21]:
event_details.to_csv(f'raw_data/event_details_{TARGET_YEAR}.csv', index=False)

In [22]:
event_results.to_csv(f'raw_data/event_results_{TARGET_YEAR}.csv', index=False)

In [23]:
events.to_csv(f'raw_data/events_{TARGET_YEAR}.csv', index=False)